### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by snmslavk** [mchudinov/ServiceDemon#1]
Do you think this approach has some advantages over standard WindowsServices as I‘ve read that mono-service has memory leak problems?

**Comment by mchudinov** [comment]
I know nothing about mono memory leaks. This approach has an advantage if only a Mono-based platform (Linux) is available and standard WindowsServices is just impossible there. Why would you want to use Linux-hosting? Well, it is cheaper. It has lightweight containers like Docker. 
I used this setup in production without restart for at least a couple of months and did not notice any memory leaks.
